[[plugins]]
package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/"
  to = "/swap"
  status = 302
  force = true # COMMENT: ensure that we always redirect

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors 'none';"