[[plugins]]
package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "."
  to = "/swap"
  status = 301
  force = true # COMMENT: ensure that we always redirect

[[redirects]]
  from = "/index.html"
  to = "/swap"
  status = 301
  force = true # COMMENT: ensure that we always redirect